In [27]:

import torch
from torch import nn

import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import Vocab
from torchtext.legacy.data import Field, TabularDataset, BucketIterator, Iterator
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import DataLoader, TensorDataset

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')



In [28]:

import pandas as pd

train_data = pd.read_csv("./train_eng.csv", header=0, engine='python' ,encoding = "latin-1", usecols=["Name","Gender"])
test_data = pd.read_csv("./test_eng.csv", header=0, engine='python' ,encoding = "latin-1", usecols=["Name","Gender"])

test_data['Gender'] = test_data['Gender'].apply(lambda x: 0 if x=='M' else 1)
train_data['Gender'] = train_data['Gender'].apply(lambda x: 0 if x=='M' else 1)


#print(train_data.shape)
#train_data = train_data[:1280]
#test_data = test_data[:1280]
#print(train_data.shape)

train_data = train_data.sort_values(by="Name", key=lambda x: x.str.len())
test_data = test_data.sort_values(by="Name", key=lambda x: x.str.len())

max_length_test = len(test_data.iloc[-1]['Name'])
max_length_train = len(train_data.iloc[-1]['Name'])
max_length = max(max_length_test, max_length_train)

unique = list(set("".join(train_data.iloc[:,0])))
unique.sort()
vocab = dict(zip(unique, range(1,len(unique)+1)))

tokenizer = get_tokenizer('basic_english')

vocab_new = Vocab(vocab,specials=())

def data_process(raw_text_iter,max_len=128):
  batch = []
  for item in raw_text_iter:
    res = []
    for i in range(max_len):
      if (len(item)>i):
        res.extend([vocab_new[token] for token in tokenizer(item[i])])
      else:
        res.extend([0])
    batch.append(res)
  pad_data = torch.FloatTensor(batch)
  return pad_data



In [29]:

import numpy as np
from torch.utils.data import DataLoader, TensorDataset
scaler = MinMaxScaler(feature_range=(-1, 1))

max_len = 64
embedding_size = max(max_length_train, max_length_test)
n_classes = len(np.unique(train_data.Gender.values))

#Create Dataloader
train_tensor = data_process(train_data.Name.values, embedding_size)
train_data_normalized = torch.FloatTensor(scaler.fit_transform(train_tensor))
tgts_tensor = torch.nn.functional.one_hot(torch.from_numpy(train_data.Gender.values), n_classes) #torch.from_numpy(train_data.Target.values)

dataset = TensorDataset(train_data_normalized, tgts_tensor)

loader = DataLoader(dataset, batch_size=128, shuffle=True, pin_memory=True)

tensor([[ 0.9200,  0.5200, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [ 0.9200,  0.6800, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [-0.1200,  0.8400, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        ...,
        [ 0.8400,  0.4400, -0.3600,  ...,  0.3600,  0.8400,  0.4400],
        [ 0.2000,  0.6800, -0.6800,  ..., -0.2000,  0.4400,  0.6800],
        [ 0.2800, -0.1200, -0.0400,  ...,  1.0000,  0.6800,  0.1200]])
tensor([[ 0.9200,  0.5200, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [ 0.9200,  0.6800, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [-0.1200,  0.8400, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        ...,
        [ 0.8400,  0.4400, -0.3600,  ...,  0.3600,  0.8400,  0.4400],
        [ 0.2000,  0.6800, -0.6800,  ..., -0.2000,  0.4400,  0.6800],
        [ 0.2800, -0.1200, -0.0400,  ...,  1.0000,  0.6800,  0.1200]])

tensor([[0, 1],
        [1, 0],
        [1, 0],
        ...,
        [1, 0],
        [1, 0],
        [1, 0]])

tensor([[ 0.9200,  0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [35]:

class noLSTM(torch.nn.Module):
  def __init__(self, input_size=max_length, hidden_layer_size=100, output_size=2):
        super().__init__()
        self.input_size = input_size
        self.hidden_layer_size = hidden_layer_size
        self.linear_one = nn.Linear(input_size, hidden_layer_size)
        self.linear = nn.Linear(hidden_layer_size, output_size)
        self.hidden_cell = (torch.zeros(1,1,self.hidden_layer_size),
                            torch.zeros(1,1,self.hidden_layer_size))

  def forward(self, input_seq):
        #input_seq = torch.reshape(input_seq, shape=(-1, self.input_size * input_seq.shape[0]))
        #lstm_output.view(self.input_size * input_seq.shape, -1)
        #lstm_out, self.hidden_cell = self.linear_one(input_seq.view(len(input_seq) ,1, -1), self.hidden_cell)
        x = self.linear_one(input_seq)
        predictions = self.linear(x)
        return predictions

model = noLSTM()
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


In [31]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()

In [36]:
import time 

epochs = 50
import torch.nn.functional as F

start_time = time.time()

losses = []
acc = []
measures = []
times = []
i_array = []

for i in range(epochs):
    correct = 0
    total = 0
    start_epoch = time.time()
    for item in loader:
        seq = item[0]
        label = item[1]
        optimizer.zero_grad()
        model.hidden_cell = (torch.zeros(1, 1, model.hidden_layer_size),
                        torch.zeros(1, 1, model.hidden_layer_size))
        
        y_pred = model(seq)
        for j in range(y_pred.shape[0]):
          predicted = np.argmax(F.softmax(y_pred[j].data))
          true = np.argmax(label[j].data)
          if (predicted == true):
            correct+=1
          total+=1
        single_loss = loss_function(y_pred, label.float())
        single_loss.backward()
        optimizer.step()

    time_per_epoch = time.time() - start_epoch
    f_measure = f1_loss(label, y_pred)
    i_array.append(i)
    writer.add_scalar("train_loss", single_loss.item(), i)
    losses.append(single_loss.item())
    writer.add_scalar("train_acc", (100 * correct / total), i)
    acc.append((100 * correct / total))
    writer.add_scalar("train_measure", f_measure, i)
    measures.append(f_measure)
    writer.add_scalar("train_time", time_per_epoch, i)
    times.append(time_per_epoch)
    for tag, parm in model.named_parameters():
      writer.add_histogram(tag, parm.grad.data.cpu().numpy(), i)
    print(f'epoch: {i:3} loss: {single_loss.item():10.8f}, accuracy: {(100 * correct / total)}, f-measure: {f_measure}, time = {time_per_epoch}')

print("MODEL TIME EXECUTION--- %s seconds ---" % (time.time() - start_time_model))
print(f'epoch: {i:3} loss: {single_loss.item():10.10f}')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


epoch:   0 loss: 0.22485100, accuracy: 62.78095283834406, f-measure: 0.5258151292800903, time = 18.144066333770752
epoch:   1 loss: 0.21679424, accuracy: 62.608058783978485, f-measure: 0.5347089171409607, time = 18.92706537246704
epoch:   2 loss: 0.20638941, accuracy: 62.86019594659495, f-measure: 0.5311689972877502, time = 18.302782773971558
epoch:   3 loss: 0.24706711, accuracy: 62.91782729805014, f-measure: 0.5150653123855591, time = 18.354072332382202
epoch:   4 loss: 0.23457107, accuracy: 63.03309000096052, f-measure: 0.5284972786903381, time = 18.462736129760742
epoch:   5 loss: 0.21160230, accuracy: 62.95985015848622, f-measure: 0.5328078866004944, time = 19.036044597625732
epoch:   6 loss: 0.21624094, accuracy: 63.109931802900775, f-measure: 0.5314635634422302, time = 18.800137758255005
epoch:   7 loss: 0.22728513, accuracy: 63.0823167803285, f-measure: 0.5240451097488403, time = 19.40931463241577
epoch:   8 loss: 0.24202885, accuracy: 63.02588608202862, f-measure: 0.5164480209

NameError: ignored

In [26]:
def f1_loss(y_true:torch.Tensor, y_pred:torch.Tensor, is_training=False) -> torch.Tensor:
    all = y_pred.shape[0]
    sum=0
    for i in range(all):
      sum+=f1_loss_one(y_true[i], y_pred[i])
    return sum/all

def f1_loss_one(y_true:torch.Tensor, y_pred:torch.Tensor, is_training=False) -> torch.Tensor:
    y_pred_soft = (F.softmax(((y_pred)), dim=0)).detach()
    if y_pred_soft.ndim == 2:
        y_pred_soft = y_pred_soft.argmax(dim=1)
    if y_true.ndim == 2:
        y_true = y_true.argmax(dim=1)
    
    tp = (y_true * y_pred_soft).sum().to(torch.float32)
    tn = ((1 - y_true) * (1 - y_pred_soft)).sum().to(torch.float32)
    fp = ((1 - y_true) * y_pred_soft).sum().to(torch.float32)
    fn = (y_true * (1 - y_pred_soft)).sum().to(torch.float32)
    
    epsilon = 1e-7
    
    precision = tp / (tp + fp + epsilon)
    recall = tp / (tp + fn + epsilon)
    
    f1 = 2* (precision*recall) / (precision + recall + epsilon)
    #f1.requires_grad = is_training
    return f1

In [39]:
print(test_data)
scaler = MinMaxScaler(feature_range=(-1, 1))

max_len = 64
embedding_size = max(max_length_train, max_length_test)
n_classes = len(np.unique(test_data.Gender.values))

#Create Dataloader
test_tensor = data_process(test_data.Name.values, embedding_size)
test_data_normalized = torch.FloatTensor(scaler.fit_transform(test_tensor))
test_tgts_tensor = torch.nn.functional.one_hot(torch.from_numpy(test_data.Gender.values), n_classes) #torch.from_numpy(train_data.Target.values)

test_dataset = TensorDataset(test_data_normalized, test_tgts_tensor)

loader = DataLoader(dataset, batch_size=128, shuffle=True, pin_memory=True)

                  Name  Gender
20199               Ar       0
2786                Lc       0
3902                Si       0
8554                Ji       0
19970               Za       0
...                ...     ...
14096  Christiananthon       0
18070  Christianalexan       0
16548  Matthewalexande       0
10920  Ashleyelizabeth       1
11332  Christopherryan       0

[20822 rows x 2 columns]
tensor([[ 1.0000, -0.3600, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [ 0.1200,  0.8400, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [-0.4400,  0.3600, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        ...,
        [ 0.0400,  1.0000, -0.5200,  ..., -0.0400,  0.7600,  1.0000],
        [ 1.0000, -0.4400,  0.4400,  ...,  0.6800, -0.5200,  0.7143],
        [ 0.8400,  0.4400, -0.3600,  ..., -0.9200,  1.0000,  0.1429]])
tensor([[ 1.0000, -0.3600, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [ 0.1200,  0.8400, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [-0.4400,  0.3600, -

In [41]:
torch.save(model.state_dict(), 'model.pt')

In [54]:
model.load_state_dict(torch.load('model.pt'))
test_loss, test_acc = evaluate_model(model, loader, loss_function)
print(f'Accuracy on test data : {test_acc*100:.2f}%')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  del sys.path[0]


Accuracy on test data : 63.70%


In [53]:
def evaluate_model(model, data_batches, loss_function):
  eval_loss = 0
  eval_acc = 0
  
  model.eval()
  
  with torch.no_grad():
    for batch in data_batches:
      correct = 0
      total = 0
      predictions = model(batch[0]).squeeze(1)
      for j in range(predictions.shape[0]):
          predicted = np.argmax(F.softmax(predictions[j].data))
          true = np.argmax(batch[1][j].data)
          if (predicted == true):
            correct+=1
          total+=1
      loss = loss_function(predictions, batch[1])
      
      #acc = accuracy_calculator(predictions, batch[1])
      eval_loss += loss.item()
      eval_acc += (correct / total)
  
  return eval_loss / len(data_batches), eval_acc / len(data_batches)